/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StaffRouteRouteImport } from './routes/staff/route'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AppAnnouncementsRouteImport } from './routes/app/announcements'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppRecordsRouteImport } from './routes/app/records'
import { Route as AppServicesRouteImport } from './routes/app/services'
import { Route as StaffAnnouncementsRouteImport } from './routes/staff/announcements'
import { Route as StaffAppointmentsRouteImport } from './routes/staff/appointments'
import { Route as StaffDashboardRouteImport } from './routes/staff/dashboard'
import { Route as StaffNotificationsRouteImport } from './routes/staff/notifications'
import { Route as AppAppointmentsIndexRouteImport } from './routes/app/appointments/index'
import { Route as AppAppointmentsNewRouteImport } from './routes/app/appointments/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRouteRoute,
} as any)
const StaffAnnouncementsRoute = StaffAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffAppointmentsRoute = StaffAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffNotificationsRoute = StaffNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StaffRouteRoute,
} as any)
const AppAppointmentsIndexRoute = AppAppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppointmentsNewRoute = AppAppointmentsNewRouteImport.update({
  id: '/appointments/new',
  path: '/appointments/new',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/records': typeof AppRecordsRoute
  '/app/services': typeof AppServicesRoute
  '/staff/announcements': typeof StaffAnnouncementsRoute
  '/staff/appointments': typeof StaffAppointmentsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/app/appointments/new': typeof AppAppointmentsNewRoute
  '/app/appointments/': typeof AppAppointmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/records': typeof AppRecordsRoute
  '/app/services': typeof AppServicesRoute
  '/staff/announcements': typeof StaffAnnouncementsRoute
  '/staff/appointments': typeof StaffAppointmentsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/app/appointments/new': typeof AppAppointmentsNewRoute
  '/app/appointments': typeof AppAppointmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/records': typeof AppRecordsRoute
  '/app/services': typeof AppServicesRoute
  '/staff/announcements': typeof StaffAnnouncementsRoute
  '/staff/appointments': typeof StaffAppointmentsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/notifications': typeof StaffNotificationsRoute
  '/app/appointments/new': typeof AppAppointmentsNewRoute
  '/app/appointments/': typeof AppAppointmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/staff'
    | '/announcements'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/app/announcements'
    | '/app/dashboard'
    | '/app/notifications'
    | '/app/records'
    | '/app/services'
    | '/staff/announcements'
    | '/staff/appointments'
    | '/staff/dashboard'
    | '/staff/notifications'
    | '/app/appointments/new'
    | '/app/appointments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/staff'
    | '/announcements'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/app/announcements'
    | '/app/dashboard'
    | '/app/notifications'
    | '/app/records'
    | '/app/services'
    | '/staff/announcements'
    | '/staff/appointments'
    | '/staff/dashboard'
    | '/staff/notifications'
    | '/app/appointments/new'
    | '/app/appointments'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/staff'
    | '/announcements'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/app/announcements'
    | '/app/dashboard'
    | '/app/notifications'
    | '/app/records'
    | '/app/services'
    | '/staff/announcements'
    | '/staff/appointments'
    | '/staff/dashboard'
    | '/staff/notifications'
    | '/app/appointments/new'
    | '/app/appointments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  StaffRouteRoute: typeof StaffRouteRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/app/announcements': {
      id: '/app/announcements'
      path: '/announcements'
      fullPath: '/app/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/records': {
      id: '/app/records'
      path: '/records'
      fullPath: '/app/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/services': {
      id: '/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/staff/announcements': {
      id: '/staff/announcements'
      path: '/announcements'
      fullPath: '/staff/announcements'
      preLoaderRoute: typeof StaffAnnouncementsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/appointments': {
      id: '/staff/appointments'
      path: '/appointments'
      fullPath: '/staff/appointments'
      preLoaderRoute: typeof StaffAppointmentsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/notifications': {
      id: '/staff/notifications'
      path: '/notifications'
      fullPath: '/staff/notifications'
      preLoaderRoute: typeof StaffNotificationsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/app/appointments/': {
      id: '/app/appointments/'
      path: '/appointments'
      fullPath: '/app/appointments/'
      preLoaderRoute: typeof AppAppointmentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/appointments/new': {
      id: '/app/appointments/new'
      path: '/appointments/new'
      fullPath: '/app/appointments/new'
      preLoaderRoute: typeof AppAppointmentsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppRecordsRoute: typeof AppRecordsRoute
  AppServicesRoute: typeof AppServicesRoute
  AppAppointmentsNewRoute: typeof AppAppointmentsNewRoute
  AppAppointmentsIndexRoute: typeof AppAppointmentsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppRecordsRoute: AppRecordsRoute,
  AppServicesRoute: AppServicesRoute,
  AppAppointmentsNewRoute: AppAppointmentsNewRoute,
  AppAppointmentsIndexRoute: AppAppointmentsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface StaffRouteRouteChildren {
  StaffAnnouncementsRoute: typeof StaffAnnouncementsRoute
  StaffAppointmentsRoute: typeof StaffAppointmentsRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffNotificationsRoute: typeof StaffNotificationsRoute
}

const StaffRouteRouteChildren: StaffRouteRouteChildren = {
  StaffAnnouncementsRoute: StaffAnnouncementsRoute,
  StaffAppointmentsRoute: StaffAppointmentsRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffNotificationsRoute: StaffNotificationsRoute,
}

const StaffRouteRouteWithChildren = StaffRouteRoute._addFileChildren(
  StaffRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  StaffRouteRoute: StaffRouteRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
